### PR TITLE
Custom Editor Patch.

### PR DESCRIPTION
**Pull request by DelinWorks**
Working on a custom TileMap renderer that can render tiles according to layers and textures, can be edited real time with extremely fast performance and minimum memory usage. Editor will have all basic features like, place, stamp, remove, select, move, etc...

### CODE REVIEW

**Comment by aismann** [comment]
Maybe the NEW "Tiled/Level Editor" for axmol also?

**Comment by DelinWorks** [comment]
@aismann you know that might actually be a great idea! 👍 I'll do it when I'm finished with the editor

**Comment by aismann** [comment]
Yes I know ;)
And maybe this is the solution for the multi-tileset layers issue too ;)

**Comment by DelinWorks** [comment]
Editor will be delayed but will still be used for Rebound, A new simpler idea that uses Tiles will be implemented

**Pull request merged**
