### PR TITLE
Custom UI Patch

### PR DESCRIPTION
**Pull request by DelinWorks**
working on advanced and simple Ui for the editor and the whole game, Editor panels and layout types will be implemented to ease the Ui workflow and design.

### CODE REVIEW

**Comment by aismann** [comment]
Can it build with the axmol nativ version or need I a custom axmol version?

**Comment by DelinWorks** [comment]
@aismann You need the custom version of axmol, unfortunately.. Some features require modifying the engine itself, and I can't do a pull request for everything I change in the engine, you know 😅

**Comment by aismann** [comment]
@DelinWorks 
Can we see something (screenshot, etc) about the tool/game?

**Comment by DelinWorks** [comment]
@aismann Done! go look at the releases

**Comment by aismann** [comment]
@DelinWorks 
Maybe time for a next viewing of your work? ;)

**Pull request merged**
